import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
import { access, readFile, writeFile } from "node:fs/promises";
import { abi, createClient, isSuccessful } from "genlayer-js";
import { studioDevnet } from "genlayer-js/chains";

const ROOT = "C:/Users/DELL/Sentinel", RPC = "https://studio-next.genlayer.com/api", CHAIN_ID = 61997;
const SMOKE = process.env.SENTINEL_MIGRATION_SMOKE === "1";
const SMOKE_DIR = process.env.SENTINEL_MIGRATION_SMOKE_DIR || "migration-smoke-regression-fix";
const RECOVERY_COOLDOWN = SMOKE ? 5n : 900n;
const OWNER = "0xb1e3ea743df2b006b66751d57337c2bb10e23ecc", ACTOR = "0x6311de989ab01ae4da77d36cc45d495fbcd4b7a8";
const FAILURE = "unauthorized-drain", PROTOCOL_ID = "sentinel-demo", ADVISORY_PREFIX = "https://raw.githubusercontent.com/GIFTEDLOV/sentinel-evidence/main/evidence/advisories/";
const OUT_DIR = `${ROOT}/deploy/evidence/${SMOKE ? SMOKE_DIR : (process.env.SENTINEL_FINAL_OUTPUT_DIR || "final-production")}`, JOURNAL_PATH = `${OUT_DIR}/FINAL_TRANSACTION_JOURNAL.json`, STATE_PATH = `${OUT_DIR}/FINAL_RUN_STATE.json`, FEE_PROFILE_PATH = `${ROOT}/deploy/evidence/final-v5/STUDIO_NEXT_FEE_PROFILE.json`, EVIDENCE_REPO = `${ROOT}/_sentinel-evidence-publish`;
const safe = (v) => JSON.parse(JSON.stringify(v ?? null, (_, x) => typeof x === "bigint" ? x.toString() : x));
const lower = (v) => String(v ?? "").toLowerCase();
const first = (v, names) => { for (const n of names) if (v && v[n] !== undefined && v[n] !== null) return v[n]; return null; };
function terminal(r) { return { status: first(r, ["statusName", "status_name", "status"]), consensus: first(r, ["resultName", "result_name", "consensusStatus", "consensus_status", "consensus"]), execution: first(r, ["txExecutionResultName", "tx_execution_result_name", "txExecutionResult", "execution"]) }; }
function shaBytes(b) { return createHash("sha256").update(b).digest("hex"); }
async function loadSdk() {
  const p = "C:/Users/DELL/AppData/Roaming/npm/node_modules/genlayer/dist/index.js", s = await readFile(p, "utf8"), m = "initializeCLI();", e = s.lastIndexOf(m);
  let t = s.slice(0, e) + s.slice(e + m.length); const u = new URL(`file://${p.replaceAll("\\", "/")}`).href;
  t = t.replaceAll("import.meta.url", `new URL(${JSON.stringify(u)}).href`).replace(/export \{\s*initializeCLI\s*\};\s*$/m, "export { BaseAction };").replaceAll("fs2.chmodSync(this.folderPath, 448);", "try { fs2.chmodSync(this.folderPath, 448); } catch {};").replaceAll("fs2.chmodSync(this.keystoresPath, 448);", "try { fs2.chmodSync(this.keystoresPath, 448); } catch {};");
  const req = createRequire(p), builtins = new Set(["assert", "buffer", "child_process", "crypto", "events", "fs", "fs/promises", "http", "https", "module", "net", "os", "path", "process", "stream", "stream/promises", "string_decoder", "tty", "url", "util", "zlib"]);
  t = t.replace(/(from\s+|import\(\s*)(["'])([^"']+)(\2)/g, (a, pre, q, spec, close) => { if (spec.startsWith("node:") || spec.startsWith(".") || spec.startsWith("/")) return a; if (builtins.has(spec)) return `${pre}${q}node:${spec}${close}`; return `${pre}${q}${new URL(`file://${req.resolve(spec).replaceAll("\\", "/")}`).href}${close}`; });
  return import(`data:text/javascript;base64,${Buffer.from(t).toString("base64")}`);
}
const sdk = await loadSdk();
let journal = JSON.parse(await readFile(JOURNAL_PATH, "utf8")), state = JSON.parse(await readFile(STATE_PATH, "utf8"));
async function persist() { await writeFile(JOURNAL_PATH, JSON.stringify(safe(journal), null, 2) + "\n"); await writeFile(STATE_PATH, JSON.stringify(safe(state), null, 2) + "\n"); }
async function update(p) { state = { ...state, ...safe(p) }; await persist(); }
async function record(e) { journal.entries.push(safe(e)); await persist(); }
function chain() { return { ...studioDevnet, id: CHAIN_ID, name: "GenLayer Studio Next", nativeCurrency: { ...studioDevnet.nativeCurrency, name: "GEN", symbol: "GEN", decimals: 18 }, rpcUrls: { default: { http: [RPC] } } }; }
async function clientFor(alias) { const a = new sdk.BaseAction(); a.accountOverride = alias; const account = await a.getAccount(false); const client = createClient({ chain: chain(), endpoint: RPC, account }); return { account, client }; }
async function preflight(client, account, role) { const [c, l, n, p] = await Promise.all([client.request({ method: "eth_chainId" }), client.request({ method: "eth_getBalance", params: [account.address, "latest"] }), client.request({ method: "eth_getTransactionCount", params: [account.address, "latest"] }), client.request({ method: "eth_getTransactionCount", params: [account.address, "pending"] })]); const out = { role, account: account.address, rpc: RPC, chainId: Number.parseInt(c, 16), balanceWei: BigInt(l).toString(), latestNonce: Number.parseInt(n, 16), pendingNonce: Number.parseInt(p, 16) }; if (out.chainId !== CHAIN_ID || lower(out.account) !== (role === "actor" ? ACTOR : OWNER) || out.latestNonce !== out.pendingNonce) throw new Error(`preflight failed ${JSON.stringify(out)}`); return out; }
async function read(c, a, f, args = []) { return c.readContract({ address: a, functionName: f, args, jsonSafeReturn: true }); }
async function target(c) { return { paused: await read(c, state.demoAddress, "is_paused"), remediated: await read(c, state.demoAddress, "is_remediated"), treasury: await read(c, state.demoAddress, "get_treasury_state"), lastOutflow: await read(c, state.demoAddress, "get_last_outflow"), totalProcessed: await read(c, state.demoAddress, "get_total_processed"), counters: await read(c, state.demoAddress, "get_pause_counters") }; }
async function waitUntilPaused(c) { for (let n = 0; n < 24; n += 1) { const t = await target(c); if (t.paused) return t; await new Promise((resolve) => setTimeout(resolve, 5000)); } throw new Error("pause child message did not materialize"); }
function argsData(method, args) { const e = abi.calldata.encode(abi.calldata.makeCalldataObject(undefined, args, undefined)), raw = abi.calldata.decode(e).get("args"), d = Array.isArray(raw) ? raw : []; if (d.length !== args.length) throw new Error(`${method}: ABI roundtrip failed`); return { method, encoded: `0x${Buffer.from(e).toString("hex")}`, decoded: safe(d) }; }
async function fees(c, account, address, fn, args, allowFallback = false) {
  try {
    const f = address ? await c.estimateTransactionFeesForWrite({ account, address, functionName: fn, args, appealRounds: 1n, rotations: [0n, 0n] }) : await c.estimateTransactionFees({ account, appealRounds: 1n, rotations: [0n, 0n] });
    if (BigInt(f.feeValue) <= 0n) throw new Error("zero estimate");
    return { fees: f, method: "current genlayer-js estimateTransactionFees policy path" };
  } catch (e) {
    if (fn === "assess_incident" || fn === "assess_recovery") {
      const r = e?.cause?.data?.receipt ?? {};
      console.error(`FEE_ESTIMATE_DIAG ${fn}`, JSON.stringify({ message: String(e?.message ?? e).slice(0, 400), shortMessage: e?.shortMessage, details: e?.details, receipt: { result_name: r.result_name, execution: r.txExecutionResultName, created_timestamp: r.created_timestamp, current_timestamp: r.current_timestamp, eq_output_keys: Object.keys(r.eq_outputs ?? {}), genvm: { error_code: r.genvm_result?.error_code, raw_error: r.genvm_result?.raw_error, error_description: r.genvm_result?.error_description }, execution_stats: r.execution_stats } }));
    }
    const profileHash = SMOKE && fn === "assess_incident" ? state.advisoryEvidenceTx : allowFallback && fn === "begin_recovery" ? state.remediationTx : null;
    if (profileHash) {
      const response = await (await fetch(RPC, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "eth_getTransactionByHash", params: [profileHash] }) })).json();
      const measured = response.result?.fees;
      if (!measured?.distribution || BigInt(measured.deposit ?? 0) <= 0n) throw new Error(`no measured same-chain fee envelope for ${fn} fallback`);
      const d = measured.distribution, headroom = 2n;
      return { fees: { distribution: { leaderTimeunitsAllocation: BigInt(d.leaderTimeunitsAllocation), validatorTimeunitsAllocation: BigInt(d.validatorTimeunitsAllocation), appealRounds: BigInt(d.appealRounds), executionBudgetPerRound: BigInt(d.executionBudgetPerRound) * headroom, totalMessageFees: BigInt(d.totalMessageFees), rotations: d.rotations.map(BigInt), maxPriceGenPerTimeUnit: BigInt(d.maxPriceGenPerTimeUnit), storageFeeMaxGasPrice: BigInt(d.storageFeeMaxGasPrice), receiptFeeMaxGasPrice: BigInt(d.receiptFeeMaxGasPrice) }, feeValue: BigInt(measured.deposit) * headroom, policy: { enabled: true, genPerTimeUnit: 1n, storageUnitPrice: 250000000n, receiptGasPrice: 250000000n, executionBudgetFloor: 76548000000000n, timeUnitOverlayBps: 1500n } }, method: `measured finalized same-chain ${fn === "begin_recovery" ? "remediation" : "advisory-bind"} envelope x${headroom} headroom; estimator failed before nondeterministic execution: ${String(e?.details ?? e?.message ?? e).slice(0, 160)}` };
    }
    if (!allowFallback) throw e;
    const p = JSON.parse(await readFile(FEE_PROFILE_PATH, "utf8")).finalFeeValues.protectedDemoDeployment, d = p.distribution;
    return { fees: { leaderTimeunitsAllocation: BigInt(d.leaderTimeunitsAllocation), validatorTimeunitsAllocation: BigInt(d.validatorTimeunitsAllocation), appealRounds: BigInt(d.appealRounds), executionBudgetPerRound: BigInt(d.executionBudgetPerRound), totalMessageFees: BigInt(d.totalMessageFees), rotations: d.rotations.map(BigInt), maxPriceGenPerTimeUnit: BigInt(d.maxPriceGenPerTimeUnit), storageFeeMaxGasPrice: BigInt(d.storageFeeMaxGasPrice), receiptFeeMaxGasPrice: BigInt(d.receiptFeeMaxGasPrice), transactionHashVariant: "latest-nonfinal", feeValue: BigInt(p.feeValue) }, method: `measured current Studio Next v0.6 profile fallback: ${String(e).slice(0, 240)}` };
  }
}
async function waitSame(c, hash, label) { const decision = await c.waitForDecision({ hash, interval: 5000, retries: 120, fullTransaction: true }); const final = await c.waitForFinalization({ hash, interval: 5000, retries: 120, fullTransaction: true }); if (!isSuccessful(final)) throw new Error(`${label}: isSuccessful false ${JSON.stringify(terminal(final))}`); return { decision: terminal(decision), final: terminal(final), receipt: safe(final) }; }
function extractHash(e) { return String(e?.message ?? e).match(/0x[a-fA-F0-9]{64}/)?.[0] ?? null; }
async function op({ label, alias = "beacon-final-deployer", role = "owner", address, fn, args, before, after, timeGate = false }) {
  const { account, client } = await clientFor(alias), beforeState = await before(client), pre = await preflight(client, account, role), call = argsData(fn, args), fi = await fees(client, account, address, fn, args, timeGate);
  let simulation;
  try {
    simulation = await client.simulateWriteContract({ account, address, functionName: fn, args, fees: fi.fees, includeReceipt: true, transactionHashVariant: "latest-nonfinal" });
  } catch (e) {
    const msg = String(e?.shortMessage ?? e?.message ?? e), rec = e?.cause?.data?.receipt ?? e?.data?.receipt ?? {};
    let decodedResult = "";
    try { decodedResult = typeof rec.result === "string" ? Buffer.from(rec.result, "base64").toString("utf8").replace(/[\u0000-\u001f]+/g, " ").trim() : ""; } catch {}
    if (fn === "assess_incident" || fn === "assess_recovery") {
      const r = e?.cause?.data?.receipt ?? e?.data?.receipt ?? {};
      console.error(`SIMULATION_DIAG ${fn}`, JSON.stringify({ message: msg.slice(0, 400), result_name: r.result_name, execution: r.txExecutionResultName, current_timestamp: r.current_timestamp, eq_output_keys: Object.keys(r.eq_outputs ?? {}), genvm: { error_code: r.genvm_result?.error_code, raw_error: r.genvm_result?.raw_error, error_description: r.genvm_result?.error_description }, execution_stats: r.execution_stats }));
    }
    if (!timeGate || !(msg.includes("Recovery cooldown has not elapsed") || decodedResult.includes("Recovery cooldown has not elapsed"))) throw new Error(`${label}: simulation rejected ${msg}`);
    const simNow = BigInt(String(rec.current_timestamp ?? rec.created_timestamp ?? "1732603362")), l = await client.request({ method: "gen_getTransactionLifecycle", params: [{ txId: state.confirmPauseTx }] }), now = BigInt(String(l.evaluatedAt ?? l.evaluated_at)), anchor = BigInt(String(state.pauseConfirmedAt)), eligible = anchor + RECOVERY_COOLDOWN, margin = SMOKE ? 0n : 60n;
    if (now < eligible + margin || simNow >= eligible) throw new Error(`known stale clock contradiction not proven ${JSON.stringify({ simNow: simNow.toString(), now: now.toString(), anchor: anchor.toString(), eligible: eligible.toString(), margin: margin.toString() })}`);
    simulation = { status: "KNOWN_STALE_CLOCK_FALSE_NEGATIVE", exactError: decodedResult || msg, simulatedGenVmNow: simNow.toString(), canonicalNodeNow: now.toString(), recoveryEligibleAt: eligible.toString() };
    await update({ simulationFalseNegative: { ...simulation, proven: true } });
  }
  const bp = await preflight(client, account, role); if (bp.latestNonce !== pre.latestNonce) throw new Error(`${label}: nonce changed before broadcast`); let tx; try { tx = await client.writeContract({ account, address, functionName: fn, args, fees: fi.fees }); } catch (e) { const h = extractHash(e); await record({ label, fn, address, nonce: bp.latestNonce, fees: safe(fi.fees), feeMethod: fi.method, simulation: safe(simulation), broadcastCount: 1, ambiguousHash: h, submissionError: String(e) }); throw new Error(`${label}: submission failed${h ? ` after ${h}` : ""}; refusing retry`); }
 await record({ label, txHash: tx, fn, address, nonce: bp.latestNonce, args: safe(args), fees: safe(fi.fees), feeMethod: fi.method, simulation: safe(simulation), broadcastCount: 1, phase: "SUBMITTED" }); const t = await waitSame(client, tx, label), postState = await after(client, tx); await record({ label, txHash: tx, nonce: bp.latestNonce, terminal: t, postState, phase: "FINALIZED_DECIDED_EXECUTION_VERIFIED_STATE_VERIFIED" }); return { tx, client, account, postState, terminal: t, call }; }
async function rawFacts(hash) { const e = await (await fetch(RPC, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "eth_getTransactionByHash", params: [hash] }) })).json(), p = e.result ?? e, data = p.data ?? {}, input = p.input ?? p.txCallData ?? data.calldata; const facts = { consensus: String(p.result_name ?? p.consensusResultName ?? p.consensus_status).toUpperCase(), event_timestamp: Number(BigInt(String(p.created_timestamp ?? p.timestamp ?? p.createdTimestamp))), execution: String(p.txExecutionResultName ?? p.execution_result_name).toUpperCase(), hash: String(p.hash ?? p.id ?? p.tx_id).toLowerCase(), input: String(input), origin: String(p.origin_address ?? p.txOrigin ?? p.sender ?? p.from_address ?? p.from).toLowerCase(), sender: String(p.sender ?? p.from_address ?? p.from).toLowerCase(), status: String(p.status ?? p.statusName ?? p.status_name).toUpperCase(), target: String(p.recipient ?? p.to_address ?? p.to).toLowerCase() }; return { facts, digest: shaBytes(JSON.stringify(facts)), input: facts.input }; }
const KNOWN_PUBLISHED_ADVISORIES = {
  "evidence/advisories/incident-incident-b2fa64830f71.json": "1e27c04818a763716adb14d85626ea1d490b8857",
  "evidence/advisories/incident-incident-9f85596208f3.json": "4b2fb0487af78fe52ed31b0ed33d32af1f114956",
  "evidence/advisories/incident-incident-56a5dd88c9e1.json": "609bb530810849ef2284d3b0eb59f70bd2c71a62",
  "evidence/advisories/recovery-incident-56a5dd88c9e1.json": "92796cc36f8198d3dd6fd9e356e46cf671d8bd0b",
  "evidence/advisories/incident-incident-e5115f160d64.json": "d1bcb30e825a2c486220de2a0f4d5c7b648b7be3",
  "evidence/advisories/recovery-incident-e5115f160d64.json": "a8b163bd518ed100c317e1283a43db42c6bb8beb",
};
function readPublished(relative) { const commit = KNOWN_PUBLISHED_ADVISORIES[relative]; return commit ? { commit: { sha: commit } } : null; }
  function publishViaGh(relative, message) { const env = { ...process.env, GH_CONFIG_DIR: process.env.GH_CONFIG_DIR || `${ROOT}/.gh-auth`, GIT_CONFIG_GLOBAL: process.env.GIT_CONFIG_GLOBAL || `${ROOT}/.gitconfig-gh` }; for (const k of ["HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "http_proxy", "https_proxy", "all_proxy"]) delete env[k]; const run = (file, args) => execFileSync(file === "git" ? "C:/Program Files/Git/cmd/git.exe" : "C:/Program Files/GitHub CLI/gh.exe", args, { cwd: EVIDENCE_REPO, env, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim(); run("git", ["-c", "http.sslBackend=openssl", "fetch", "origin", "main"]); run("git", ["add", "--", relative]); run("git", ["commit", "-m", message]); const token = run("gh", ["auth", "token"]); if (!token) throw new Error("gh auth token returned empty"); const auth = Buffer.from(`x-access-token:${token}`).toString("base64"); run("git", ["-c", "http.sslBackend=openssl", `-c`, `http.extraHeader=Authorization: Basic ${auth}`, "push", "origin", "HEAD:main"]); return { commit: { sha: run("git", ["rev-parse", "HEAD"]) } }; }
async function advisory(kind, incidentId, tx, current, critical, mitigation, summary) { const name = `${kind}-${incidentId}.json`, rel = `evidence/advisories/${name}`, path = `${EVIDENCE_REPO}/${rel}`; let doc; try { doc = JSON.parse(await readFile(path, "utf8")); } catch (e) { if (!String(e?.code).includes("ENOENT")) throw e; doc = { schema: "sentinel-advisory-v1", protocol_id: PROTOCOL_ID, protocol_address: state.demoAddress, network: "Studio Next", canonical_rpc: RPC, incident_id: incidentId, phase: kind === "recovery" ? "RECOVERY" : "EMERGENCY", failure_class: FAILURE, status: kind === "recovery" ? "REMEDIATED" : "ACTIVE", transaction_hash: tx, issued_at: new Date().toISOString(), current, critical_signal: critical, mitigation_complete: mitigation, summary, facts: [{ name: "transaction", value: tx }, { name: "target", value: state.demoAddress }] }; await writeFile(path, JSON.stringify(doc, null, 2) + "\n"); } const body = await readFile(path); const digest = shaBytes(body); const remote = readPublished(rel); let commit = remote?.commit?.sha ?? null; if (!remote) { const published = publishViaGh(rel, `Publish final production ${kind} advisory`, body); commit = published.commit?.sha ?? null; } if (!commit) throw new Error(`advisory publication did not return commit for ${rel}`); const raw = Buffer.from(await (await fetch(`${ADVISORY_PREFIX}${name}`, { cache: "no-store" })).arrayBuffer()); if (digest !== shaBytes(raw)) throw new Error("raw advisory digest mismatch"); return { file: path, url: `${ADVISORY_PREFIX}${name}`, digest, bytes: body.length, commit, document: doc }; }

async function finishFinalProofOnly() {
  const { account: ownerAccount, client: ownerClient } = await clientFor("beacon-final-deployer");
  const priorPost = journal.entries.filter((e) => e.label === "POST_RECOVERY_PROCESS" && e.txHash).at(-1);
  let post = { tx: state.postRecoveryProcessTx ?? priorPost?.txHash ?? null };
  if (post.tx) {
    await waitSame(ownerClient, post.tx, "POST_RECOVERY_PROCESS same-hash reconciliation");
    post.postState = await target(ownerClient);
  } else {
    post = await op({ label: "POST_RECOVERY_PROCESS", address: state.demoAddress, fn: "process", args: [1n], before: async (c) => {
      const paused = await read(c, state.demoAddress, "is_paused"), remediated = await read(c, state.demoAddress, "is_remediated");
      if (paused || !remediated) throw new Error(`post process precondition failed ${JSON.stringify({ paused, remediated })}`);
      return { paused, remediated };
    }, after: async (c) => {
      const t = await target(c);
      if (String(t.totalProcessed) !== "2" || t.paused || !t.remediated || String(t.treasury.treasury_balance) !== "900" || String(t.treasury.total_outflow) !== "100") throw new Error("post process readback failed");
      return t;
    } });
  }
  const { account: playerAccount, client: playerClient } = await clientFor("player2"), finalTarget = post.postState;
  if (String(finalTarget.totalProcessed) !== "2" || finalTarget.paused || !finalTarget.remediated || String(finalTarget.treasury.treasury_balance) !== "900" || String(finalTarget.treasury.total_outflow) !== "100") throw new Error(`post recovery state failed ${JSON.stringify(safe(finalTarget))}`);
  let rejected = false, rejection = "";
  try {
    const nf = await fees(playerClient, playerAccount, state.demoAddress, "execute_outflow", [ACTOR, 1n]);
    try { await playerClient.simulateWriteContract({ account: playerAccount, address: state.demoAddress, functionName: "execute_outflow", args: [ACTOR, 1n], fees: nf.fees, includeReceipt: true, transactionHashVariant: "latest-nonfinal" }); } catch (e) { rejected = true; rejection = String(e?.shortMessage ?? e?.message ?? e); }
  } catch (e) {
    const rec = e?.cause?.data?.receipt ?? e?.data?.receipt ?? {}; let decoded = "";
    try { decoded = typeof rec.result === "string" ? Buffer.from(rec.result, "base64").toString("utf8").replace(/[\u0000-\u001f]+/g, " ").trim() : ""; } catch {}
    const msg = String(e?.shortMessage ?? e?.message ?? e); if (msg.includes("Outflow capability has been remediated") || decoded.includes("Outflow capability has been remediated")) { rejected = true; rejection = decoded || msg; } else throw e;
  }
  if (!rejected) throw new Error("permanent fix proof failed: non-owner simulation was accepted");
  await update({ postRecoveryProcessTx: post.tx, nonownerOutflowSimulation: { status: "REJECTED", error: rejection }, finalTarget, backendProtocolComplete: true, finishedAt: new Date().toISOString() });
  console.log(JSON.stringify({ stage: "BACKEND_PROTOCOL_COMPLETE", state: safe(state), journal: JOURNAL_PATH }, null, 2));
}
const lifecycleWritesComplete = state.recoveryChainEvidenceTx && state.recoveryAdvisoryEvidenceTx && state.recoveryAssessmentTx && state.unpauseTx && state.confirmRecoveredTx && !state.backendProtocolComplete;
if (lifecycleWritesComplete) { await finishFinalProofOnly(); process.exit(0); }
const owner = await clientFor("beacon-final-deployer"); let outEntry = journal.entries.filter((e) => e.label === "CONTROLLED_OUTFLOW_100" && e.txHash).at(-1);
if (!outEntry && !SMOKE && state.lockPolicyTx) {
  const priorBaseline = journal.entries.filter((e) => e.label === "HEALTHY_BASELINE" && e.txHash).at(-1); let baselineTx = state.healthyBaselineTx ?? priorBaseline?.txHash; if (baselineTx) { await waitSame(owner.client, baselineTx, "HEALTHY_BASELINE same-hash reconciliation"); const baselineState = await target(owner.client); if (String(baselineState.totalProcessed) !== "1" || baselineState.paused) throw new Error(`baseline readback failed ${JSON.stringify(safe(baselineState))}`); await update({ healthyBaselineTx: baselineTx, totalProcessedAfterBaseline: "1" }); } else { const baseline = await op({ label: "HEALTHY_BASELINE", address: state.demoAddress, fn: "process", args: [1n], before: async (c) => target(c), after: async (c) => { const t = await target(c); if (String(t.totalProcessed) !== "1" || t.paused) throw new Error("baseline readback failed"); return t; } }); await update({ healthyBaselineTx: baseline.tx, totalProcessedAfterBaseline: "1" }); }
  const priorOutflow = journal.entries.filter((e) => e.label === "CONTROLLED_OUTFLOW_100" && e.txHash).at(-1); let outflow = priorOutflow ? { tx: priorOutflow.txHash } : await op({ label: "CONTROLLED_OUTFLOW_100", alias: "player2", role: "actor", address: state.demoAddress, fn: "execute_outflow", args: [ACTOR, 100n], before: async (c) => target(c), after: async (c) => { const t = await target(c); if (t.paused || t.remediated || String(t.treasury.treasury_balance) !== "900" || String(t.treasury.total_outflow) !== "100") throw new Error(`outflow readback failed ${JSON.stringify(safe(t))}`); return t; } }); if (priorOutflow) await waitSame((await clientFor("player2")).client, priorOutflow.txHash, "CONTROLLED_OUTFLOW_100 same-hash reconciliation"); const facts = await rawFacts(outflow.tx); await update({ outflowTx: outflow.tx, outflowFacts: facts.facts, outflowDigest: facts.digest, outflowInput: facts.input }); outEntry = { label: "CONTROLLED_OUTFLOW_100", txHash: outflow.tx };
}
if (!outEntry) throw new Error("no recorded outflow to reconcile");
const outReconciled = await waitSame(owner.client, outEntry.txHash, "CONTROLLED_OUTFLOW_100 same-hash reconciliation");
const outState = await target(owner.client); const outFacts = await rawFacts(outEntry.txHash); if (String(outState.treasury.treasury_balance) !== "900" || String(outState.treasury.total_outflow) !== "100") throw new Error(`outflow state mismatch ${JSON.stringify(safe(outState))}`);
await record({ label: "CONTROLLED_OUTFLOW_100_RECONCILED", txHash: outEntry.txHash, terminal: outReconciled, postState: outState, facts: outFacts }); await update({ outflowTx: outEntry.txHash, outflowFacts: outFacts.facts, outflowDigest: outFacts.digest, outflowInput: outFacts.input });
const incidentId = state.incidentId ?? `incident-${outEntry.txHash.slice(2, 14)}`;
let opened = { tx: state.incidentCreateTx }; if (!state.incidentCreateTx) { opened = await op({ label: "CREATE_INCIDENT", address: state.sentinelAddress, fn: "open_incident", args: [incidentId, PROTOCOL_ID], before: async () => ({}), after: async (c) => read(c, state.sentinelAddress, "get_incident", [incidentId]) }); await update({ incidentId, incidentCreateTx: opened.tx }); }
const chainId = `chain-${outEntry.txHash.slice(2, 14)}`; let chainBind = { tx: state.chainEvidenceTx }; if (!state.chainEvidenceTx) { chainBind = await op({ label: "BIND_INCIDENT_CHAIN_EVIDENCE", address: state.sentinelAddress, fn: "bind_evidence", args: [incidentId, chainId, "EMERGENCY", "CHAIN_TRANSACTION", RPC, FAILURE, outFacts.digest, outEntry.txHash, 0n, outFacts.input], before: async () => ({}), after: async (c) => read(c, state.sentinelAddress, "get_evidence", [chainId]) }); await update({ chainEvidenceTx: chainBind.tx, chainEvidenceId: chainId }); }
const refreshChainId = `chain-refresh-${outEntry.txHash.slice(2, 14)}`; if (!state.chainEvidenceRefreshTx) { const refreshBind = await op({ label: "BIND_INCIDENT_CHAIN_EVIDENCE_REFRESH", address: state.sentinelAddress, fn: "bind_evidence", args: [incidentId, refreshChainId, "EMERGENCY", "CHAIN_TRANSACTION", RPC, FAILURE, outFacts.digest, outEntry.txHash, 0n, outFacts.input], before: async (c) => { const i = await read(c, state.sentinelAddress, "get_incident", [incidentId]), e = await read(c, state.sentinelAddress, "get_evidence", [chainId]); if (i.state !== "ASSESSING" || e.authenticated_status !== "VALID") throw new Error(`chain refresh precondition failed ${JSON.stringify({ i, e })}`); return { incident: i, existingChainEvidence: e }; }, after: async (c) => { const e = await read(c, state.sentinelAddress, "get_evidence", [refreshChainId]); if (e.authenticated_status !== "VALID") throw new Error(`chain refresh readback failed ${JSON.stringify(e)}`); return e; } }); await update({ chainEvidenceRefreshTx: refreshBind.tx, chainEvidenceRefreshId: refreshChainId }); }
const incAdv = state.incidentAdvisory ?? await advisory("incident", incidentId, outEntry.txHash, true, true, false, "Authenticated chain evidence establishes a current unauthorized-drain signal for the protected protocol."); const advId = `advisory-${outEntry.txHash.slice(2, 14)}`; let advBind = { tx: state.advisoryEvidenceTx }; if (!state.advisoryEvidenceTx) { advBind = await op({ label: "BIND_INCIDENT_ADVISORY", address: state.sentinelAddress, fn: "bind_evidence", args: [incidentId, advId, "EMERGENCY", "SECURITY_ADVISORY", incAdv.url, FAILURE, incAdv.digest, outEntry.txHash, 1n, ""], before: async () => ({}), after: async (c) => read(c, state.sentinelAddress, "get_evidence", [advId]) }); } await update({ incidentAdvisory: incAdv, advisoryEvidenceTx: advBind.tx, advisoryEvidenceId: advId });
let assessed = { tx: state.incidentAssessmentTx }; if (!state.incidentAssessmentTx) { assessed = await op({ label: "ASSESS_INCIDENT", address: state.sentinelAddress, fn: "assess_incident", args: [incidentId], before: async () => ({}), after: async (c) => { const i = await read(c, state.sentinelAddress, "get_incident", [incidentId]); if (i.state !== "ACTIVE_INCIDENT" || i.incident_verdict !== "ACTIVE_INCIDENT") throw new Error(JSON.stringify(i)); return i; } }); await update({ incidentAssessmentTx: assessed.tx, incidentVerdict: "ACTIVE_INCIDENT" }); }
const priorPause = journal.entries.filter((e) => e.label === "PAUSE_TARGET" && e.txHash).at(-1); let paused; if (state.pauseTx) paused = { tx: state.pauseTx }; else if (priorPause) { await waitSame(owner.client, priorPause.txHash, "PAUSE_TARGET same-hash reconciliation"); paused = { tx: priorPause.txHash, postState: await waitUntilPaused(owner.client) }; } else paused = await op({ label: "PAUSE_TARGET", address: state.sentinelAddress, fn: "execute_pause", args: [incidentId], before: async () => ({}), after: async (c) => waitUntilPaused(c) }); let confirmed = { tx: state.confirmPauseTx, postState: { incident: { pause_confirmed_at: state.pauseConfirmedAt } } }; if (!state.confirmPauseTx) confirmed = await op({ label: "CONFIRM_PAUSE", address: state.sentinelAddress, fn: "confirm_pause", args: [incidentId], before: async () => target(owner.client), after: async (c) => { const i = await read(c, state.sentinelAddress, "get_incident", [incidentId]), t = await target(c); if (i.state !== "PAUSED" || !t.paused) throw new Error("confirm pause readback"); return { incident: i, target: t }; } });
  const anchor = String(state.pauseConfirmedAt ?? confirmed.postState.incident.pause_confirmed_at); await update({ pauseTx: paused.tx, confirmPauseTx: confirmed.tx, pauseConfirmedAt: anchor });
  const priorRemediation = journal.entries.filter((e) => e.label === "REMEDIATION" && e.txHash).at(-1); let remediation = { tx: state.remediationTx, postState: state.remediationTx ? await target(owner.client) : null }; if (!state.remediationTx && priorRemediation) { await waitSame(owner.client, priorRemediation.txHash, "REMEDIATION same-hash reconciliation"); remediation = { tx: priorRemediation.txHash, postState: await target(owner.client) }; } else if (!state.remediationTx) remediation = await op({ label: "REMEDIATION", address: state.demoAddress, fn: "apply_remediation", args: [], before: async (c) => target(c), after: async (c) => { const t = await target(c); if (!t.paused || !t.remediated) throw new Error("remediation readback"); return t; } }); if (!remediation.postState || !remediation.postState.remediated) throw new Error(`remediation readback failed ${JSON.stringify(safe(remediation.postState))}`); await update({ remediationTx: remediation.tx });
  const priorBegin = journal.entries.filter((e) => e.label === "BEGIN_RECOVERY" && e.txHash).at(-1); let begin = { tx: state.beginRecoveryTx }; if (!state.beginRecoveryTx && priorBegin) { const reconciled = await waitSame(owner.client, priorBegin.txHash, "BEGIN_RECOVERY same-hash reconciliation"); const i = await read(owner.client, state.sentinelAddress, "get_incident", [incidentId]); if (i.state !== "RECOVERY_ASSESSING") throw new Error(`begin recovery readback failed ${JSON.stringify(i)}`); begin = { tx: priorBegin.txHash, terminal: reconciled, postState: i }; } else if (!state.beginRecoveryTx) begin = await op({ label: "BEGIN_RECOVERY", address: state.sentinelAddress, fn: "begin_recovery", args: [incidentId], timeGate: true, before: async (c) => { const i = await read(c, state.sentinelAddress, "get_incident", [incidentId]), t = await target(c), l = await c.request({ method: "gen_getTransactionLifecycle", params: [{ txId: confirmed.tx }] }), now = BigInt(String(l.evaluatedAt ?? l.evaluated_at)), eligible = BigInt(anchor) + RECOVERY_COOLDOWN; if (i.state !== "PAUSED" || !t.paused || !t.remediated || now < eligible + (SMOKE ? 0n : 60n)) throw new Error(`begin preflight ${JSON.stringify({ i, t, now: now.toString(), eligible: eligible.toString() })}`); return { incident: i, target: t, canonicalNodeNow: now.toString(), recoveryEligibleAt: eligible.toString() }; }, after: async (c) => { const i = await read(c, state.sentinelAddress, "get_incident", [incidentId]); if (i.state !== "RECOVERY_ASSESSING") throw new Error(JSON.stringify(i)); return i; } }); await update({ beginRecoveryTx: begin.tx, recoveryEligibleAt: String(BigInt(anchor) + RECOVERY_COOLDOWN) });
  const remFacts = await rawFacts(remediation.tx), rChainId = `recovery-chain-${remediation.tx.slice(2, 14)}`; let rChain = { tx: state.recoveryChainEvidenceTx }; if (!state.recoveryChainEvidenceTx) rChain = await op({ label: "BIND_RECOVERY_CHAIN_EVIDENCE", address: state.sentinelAddress, fn: "bind_evidence", args: [incidentId, rChainId, "RECOVERY", "CHAIN_TRANSACTION", RPC, FAILURE, remFacts.digest, remediation.tx, 0n, remFacts.input], before: async () => ({}), after: async (c) => read(c, state.sentinelAddress, "get_evidence", [rChainId]) }); await update({ recoveryChainEvidenceTx: rChain.tx, recoveryChainEvidenceId: rChainId, recoveryChainFacts: remFacts.facts });
  const recAdv = state.recoveryAdvisory ?? await advisory("recovery", incidentId, remediation.tx, false, false, true, "Remediation finalized successfully; the protected target remains paused while Sentinel evaluates recovery."), rAdvId = `recovery-advisory-${remediation.tx.slice(2, 14)}`; let rAdv = { tx: state.recoveryAdvisoryEvidenceTx }; if (!state.recoveryAdvisoryEvidenceTx) rAdv = await op({ label: "BIND_RECOVERY_ADVISORY", address: state.sentinelAddress, fn: "bind_evidence", args: [incidentId, rAdvId, "RECOVERY", "SECURITY_ADVISORY", recAdv.url, FAILURE, recAdv.digest, remediation.tx, 1n, ""], before: async () => ({}), after: async (c) => read(c, state.sentinelAddress, "get_evidence", [rAdvId]) }); await update({ recoveryAdvisory: recAdv, recoveryAdvisoryEvidenceTx: rAdv.tx, recoveryAdvisoryEvidenceId: rAdvId });
  let rAssess = { tx: state.recoveryAssessmentTx }; if (!state.recoveryAssessmentTx) rAssess = await op({ label: "ASSESS_RECOVERY", address: state.sentinelAddress, fn: "assess_recovery", args: [incidentId], before: async (c) => { const i = await read(c, state.sentinelAddress, "get_incident", [incidentId]), t = await target(c); if (i.state !== "RECOVERY_ASSESSING" || !t.paused || !t.remediated) throw new Error("recovery assessment precondition"); return { incident: i, target: t }; }, after: async (c) => { const i = await read(c, state.sentinelAddress, "get_incident", [incidentId]); if (i.state !== "RECOVERY_AUTHORIZED" || i.recovery_verdict !== "SAFE_TO_RECOVER") throw new Error(JSON.stringify(i)); return i; } }); await update({ recoveryAssessmentTx: rAssess.tx, recoveryVerdict: "SAFE_TO_RECOVER" });
  let unpause = { tx: state.unpauseTx }; if (!state.unpauseTx) unpause = await op({ label: "UNPAUSE_TARGET", address: state.sentinelAddress, fn: "execute_unpause", args: [incidentId], before: async () => ({}), after: async (c) => { const t = await target(c); if (t.paused || !t.remediated) throw new Error("unpause readback"); return t; } }); let rec = { tx: state.confirmRecoveredTx }; if (!state.confirmRecoveredTx) rec = await op({ label: "CONFIRM_RECOVERED", address: state.sentinelAddress, fn: "confirm_recovered", args: [incidentId], before: async () => ({}), after: async (c) => { const i = await read(c, state.sentinelAddress, "get_incident", [incidentId]); if (i.state !== "RECOVERED") throw new Error(JSON.stringify(i)); return i; } }); await update({ unpauseTx: unpause.tx, confirmRecoveredTx: rec.tx, finalIncidentState: "RECOVERED" });
  const priorPost = journal.entries.filter((e) => e.label === "POST_RECOVERY_PROCESS" && e.txHash).at(-1); let post = { tx: state.postRecoveryProcessTx }; if (!state.postRecoveryProcessTx && priorPost) { await waitSame(owner.client, priorPost.txHash, "POST_RECOVERY_PROCESS same-hash reconciliation"); post = { tx: priorPost.txHash, postState: await target(owner.client) }; } else if (!state.postRecoveryProcessTx) post = await op({ label: "POST_RECOVERY_PROCESS", address: state.demoAddress, fn: "process", args: [1n], before: async (c) => target(c), after: async (c) => { const t = await target(c); if (String(t.totalProcessed) !== "2" || t.paused || !t.remediated) throw new Error("post process readback"); return t; } }); const { account: pa, client: pc } = await clientFor("player2"), finalTarget = await target(owner.client); if (String(finalTarget.totalProcessed) !== "2" || finalTarget.paused || !finalTarget.remediated || String(finalTarget.treasury.treasury_balance) !== "900" || String(finalTarget.treasury.total_outflow) !== "100") throw new Error(`post recovery state failed ${JSON.stringify(safe(finalTarget))}`); let rejected = false, rejection = ""; try { const nf = await fees(pc, pa, state.demoAddress, "execute_outflow", [ACTOR, 1n]); try { await pc.simulateWriteContract({ account: pa, address: state.demoAddress, functionName: "execute_outflow", args: [ACTOR, 1n], fees: nf.fees, includeReceipt: true, transactionHashVariant: "latest-nonfinal" }); } catch (e) { rejected = true; rejection = String(e?.shortMessage ?? e?.message ?? e); } } catch (e) { const rec = e?.cause?.data?.receipt ?? e?.data?.receipt ?? {}; let decoded = ""; try { decoded = typeof rec.result === "string" ? Buffer.from(rec.result, "base64").toString("utf8").replace(/[\u0000-\u001f]+/g, " ").trim() : ""; } catch {} const msg = String(e?.shortMessage ?? e?.message ?? e); if (msg.includes("Outflow capability has been remediated") || decoded.includes("Outflow capability has been remediated")) { rejected = true; rejection = decoded || msg; } else throw e; } if (!rejected) throw new Error("permanent fix proof failed: non-owner simulation was accepted");
  await update({ postRecoveryProcessTx: post.tx, nonownerOutflowSimulation: "REJECTED", finalTarget, backendProtocolComplete: true, finishedAt: new Date().toISOString() }); console.log(JSON.stringify({ stage: "BACKEND_PROTOCOL_COMPLETE", state: safe(state), journal: JOURNAL_PATH }, null, 2));
